version: "3.9"
services:
  db:
    image: postgres:16
    container_name: crypto_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
      POSTGRES_DB: cryptodb
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
